---
language: python
services: docker

env:
  global:
    - ROLE_NAME: docker

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test
