---
- name: Get current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false
  become: true

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
    force: true
  become: true
  when: >
    docker_compose_current_version.stdout is not defined
    or docker_compose_version not in docker_compose_current_version.stdout
